In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv(r"C:\Users\s8908\Churn_Modelling.csv")

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
x=dataset.iloc[:,3:13]#1st column - include all
#2nd column - which columns
y=dataset.iloc[:,13]

In [5]:
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [6]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [7]:
#create dummy variable
Geography = pd.get_dummies(x['Geography'],drop_first = True)
Gender    = pd.get_dummies(x['Gender'],drop_first=True)

In [8]:
Gender,Geography

(      Male
 0        0
 1        0
 2        0
 3        0
 4        0
 ...    ...
 9995     1
 9996     1
 9997     0
 9998     1
 9999     0
 
 [10000 rows x 1 columns],
       Germany  Spain
 0           0      0
 1           0      1
 2           0      0
 3           0      0
 4           0      1
 ...       ...    ...
 9995        0      0
 9996        0      0
 9997        0      0
 9998        1      0
 9999        0      0
 
 [10000 rows x 2 columns])

In [9]:
x=x.drop(['Geography','Gender'], axis=1)

In [10]:
x=pd.concat([x,Gender,Geography], axis=1)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)


C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [12]:
#FEATURE SCALING
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [13]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -1.09168714,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.30102557, -1.37744033, ...,  0.91601335,
         1.75486502, -0.57369368],
       [-1.19119591, -0.94312892, -1.031415  , ..., -1.09168714,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ...,  0.91601335,
        -0.5698444 , -0.57369368],
       [-0.62420521, -0.08179119,  1.39076231, ..., -1.09168714,
        -0.5698444 ,  1.74309049],
       [-0.28401079,  0.87525072, -1.37744033, ..., -1.09168714,
         1.75486502, -0.57369368]])

In [14]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ..., -1.09168714,
         1.75486502, -0.57369368],
       [-1.31490297,  0.10961719, -1.031415  , ..., -1.09168714,
        -0.5698444 , -0.57369368],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -1.09168714,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ...,  0.91601335,
        -0.5698444 ,  1.74309049],
       [-0.00566991, -0.46460796, -0.33936434, ...,  0.91601335,
         1.75486502, -0.57369368],
       [-0.79945688, -0.84742473,  1.04473698, ...,  0.91601335,
         1.75486502, -0.57369368]])

In [16]:
import keras
from tensorflow.keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout


In [25]:
#Initalizing ANN 
classifier = Sequential()
#Adding first input layer and first hidden layer 
classifier.add(Dense(units=6, kernel_initializer='he_uniform', activation='relu', input_dim=11))


In [26]:
#Adding 2nd hidden layer
classifier.add(Dense(units=10, kernel_initializer='he_uniform', activation='relu'))


In [27]:
#Adding output layer
classifier.add(Dense(units=1, kernel_initializer='glorot_uniform', activation='sigmoid'))

In [28]:
#compiling Ann model
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [29]:
#Fitting ANN to training set 
model_history = classifier.fit(X_train, y_train, validation_split=0.33, batch_size=10, epochs=100)


Epoch 1/100
536/536 [==============================] - 4s 4ms/step - loss: 0.5456 - accuracy: 0.7511 - val_loss: 0.4757 - val_accuracy: 0.7955
Epoch 2/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4584 - accuracy: 0.7964 - val_loss: 0.4536 - val_accuracy: 0.7993
Epoch 3/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4392 - accuracy: 0.8000 - val_loss: 0.4423 - val_accuracy: 0.8027
Epoch 4/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4295 - accuracy: 0.8080 - val_loss: 0.4361 - val_accuracy: 0.8050
Epoch 5/100
536/536 [==============================] - 2s 5ms/step - loss: 0.4231 - accuracy: 0.8140 - val_loss: 0.4302 - val_accuracy: 0.8103
Epoch 6/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4175 - accuracy: 0.8188 - val_loss: 0.4266 - val_accuracy: 0.8137
Epoch 7/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4125 - accuracy: 0.8233 - val_loss: 0.4222 - val_accuracy: 0.8209

Epoch 58/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3307 - accuracy: 0.8612 - val_loss: 0.3649 - val_accuracy: 0.8485
Epoch 59/100
536/536 [==============================] - 2s 3ms/step - loss: 0.3315 - accuracy: 0.8589 - val_loss: 0.3635 - val_accuracy: 0.8501
Epoch 60/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3299 - accuracy: 0.8612 - val_loss: 0.3678 - val_accuracy: 0.8512
Epoch 61/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3308 - accuracy: 0.8589 - val_loss: 0.3626 - val_accuracy: 0.8550
Epoch 62/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3302 - accuracy: 0.8630 - val_loss: 0.3635 - val_accuracy: 0.8504
Epoch 63/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3292 - accuracy: 0.8642 - val_loss: 0.3665 - val_accuracy: 0.8482
Epoch 64/100
536/536 [==============================] - 2s 4ms/step - loss: 0.3302 - accuracy: 0.8621 - val_loss: 0.3635 - val_accuracy:

In [30]:
print(model_history.history.keys())

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])


In [31]:
#On testing data
y_pred = classifier.predict(X_test)

63/63 [==============================] - 0s 2ms/step


In [37]:
y_pred

array([[0.30139104],
       [0.32974005],
       [0.08972281],
       ...,
       [0.08413059],
       [0.1813943 ],
       [0.24787746]], dtype=float32)

In [38]:
import numpy as np

# Assuming you have the predicted probabilities in the 'predictions' variable
predicted_probabilities = y_pred

# Convert probabilities to binary predictions
threshold = 0.5
predicted_classes = (predicted_probabilities >= threshold).astype(int)

print(predicted_classes)


[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [39]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predicted_classes)
#calculate accuracy
from sklearn.metrics import accuracy_score
score = accuracy_score(predicted_classes,y_test)

In [44]:
print(cm,"confusion matrix")

[[1511   84]
 [ 191  214]] confusion matrix


In [45]:
print(score,"accuracy on train data")

0.8625 accuracy on train data
